adding MOSAIC module data
PCLAeroParams/TChem-atm pull request #64
Opened 2024-10-16 22:12 UTC by zdaq12

2024-10-17 14:50 UTC, samfrederick approved these changes
Looks good! Thanks Zach!

2024-10-21 20:49 UTC, nriemer commented on src/core/impl/TChem_Impl_MESA.hpp
> + author: Rahul A. Zaveri */
Cite the MESA paper instead of listing authors here.

2024-10-22 00:47 UTC, odiazib requested changes
Let's use AerosolModelData as an example to create this data structure: https://github.com/PCLAeroParams/TChem-atm/blob/main/src/core/TChem_AerosolModelData.cpp#L207

Note that we do not have a parser for MosaicModelData. Therefore, it is acceptable to use hard-coded values for all the structures. We must utilize dual_views to set values in host views and then synchronize them with device views

2024-10-22 00:47 UTC, odiazib commented on src/core/impl/TChem_Impl_MESA.hpp
> +    a_zsr(0, mmd.jnh4hso4) =   1.30894;
We need to set these values in a host view. Then, we should sync them to the device. For example, use a dual_view

a_zsr = real_type_2d_dual_view(do_not_init_tag("TChem-Mosaic::a_zsr"), d1, d2); // where d1 and d2 are the sizes of this view.
// Get host view
auto a_zsr_host = a_zsr.view_host();
// Set values
a_zsr_host(0, mmd.jnh4hso4) = 1.30894;
// ...
// Sync to device
a_zsr.modify_host();
a_zsr.sync_device();

2024-10-22 00:47 UTC, odiazib commented on src/core/impl/TChem_Impl_MESA.hpp
> +  mcd_real_type_2d_view a_zsr;
We must allocate these views and can create a dedicated routine for this purpose.

2024-10-22 00:51 UTC, odiazib commented
In addition, it is a good idea to create a unit test where we create an instance of the MosaicModelData.

2024-11-08 13:52 UTC, odiazib reviewed
It looks good to me. Before merging, can you try to compile and run the unit tests with GPUs?

2025-02-12 19:01 UTC, odiazib approved these changes
It looks great! I ran the test on a machine with CUDA and all tests are passing. I just added a few minor comments.

2025-02-12 22:35 UTC, merged